[package]
name = "cargo-pvm-contract-builder"
description = "Build helper for PolkaVM contract bytecode."
repository.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
publish = true

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
polkavm-linker = { workspace = true }
toml_edit = { workspace = true }
